### PR TITLE
bugfix: non-closed statement for make function

### PR DESCRIPTION
**Pull request by GlenDC**

### CODE REVIEW

**Comment by coreytrampe** [comment]
I don't know what is really causing that JS parse error, but this fixes the issue for now.

Thanks, Glen.

**Comment by coreytrampe** [comment]
Oh, duh. It's a function *expression*, and should be terminated with a semicolon.

I'm curious as to why semicolon insertion can't catch this case.

**Comment by GlenDC** [comment]
Not sure, but it's not something I would ever dare to rely on.

**Comment by coreytrampe** [comment]
Agreed.
I seem to have developed a habit of using it in function expressions, expecting the closing brace to be enough. Thanks for helping to set me straight.

**Pull request merged**
